server:
  port: 8764

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: service-ribbon
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /